# Describes the relative position of tags to the world frame

tags:
  [
      {name: 'tag_0', x: 0, y: 0, z: 0, roll: 1.570792679, pitch: 0, yaw: 0},
      {name: 'tag_1', x: 1, y: 0, z: 0, roll: 1.570792679, pitch: 0, yaw: 0}
  ]